[package]
name = "queries-rusqlite-macros"
version = "0.2.0"
edition = "2024"
rust-version = "1.95"
description = "Macros for queries-rusqlite"
license = "BSD-3-Clause"
repository = "https://github.com/woodruffw-trough/queries-rusqlite"

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[lints]
workspace = true
