[workspace]
members = ["crates/queries-rusqlite", "crates/queries-rusqlite-macros"]
resolver = "3"

[workspace.dependencies]
proc-macro2 = "1"
queries-rusqlite-macros = { version = "=0.1.0", path = "crates/queries-rusqlite-macros" }
quote = "1"
rusqlite = { version = "0.40.2", default-features = false }
syn = { version = "3", default-features = false, features = ["full", "parsing", "printing", "proc-macro", "clone-impls", "derive"] }

[workspace.lints.rust]
elided_lifetimes_in_paths = "deny"
explicit_outlives_requirements = "deny"
let_underscore_drop = "deny"
missing_docs = "deny"
unreachable_pub = "deny"
unsafe_code = "forbid"
unused_lifetimes = "deny"
unused_qualifications = "deny"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
dbg_macro = "deny"
missing_errors_doc = "deny"
missing_panics_doc = "deny"
must_use_candidate = "deny"
needless_collect = "deny"
redundant_clone = "deny"
todo = "deny"
unimplemented = "deny"
