[package]
name = "queries-rusqlite"
version = "0.2.0"
edition = "2024"
rust-version = "1.95"
description = "Declare SQLite queries as Rust methods"
repository = "https://github.com/woodruffw-trough/queries-rusqlite"
license = "BSD-3-Clause"
readme = "../../README.md"

[dependencies]
queries-rusqlite-macros.workspace = true
rusqlite.workspace = true

[lints]
workspace = true
